version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dreams_come_true-mysql-volume:/var/lib/mysql
    restart: always
    container_name: dreams_come_true_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreams_come_true
      MYSQL_USER: dragonsky
      MYSQL_PASSWORD: 235711

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
